apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  labels:
    app: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: thenewson/service:8
        env:
        - name: REDIS_OUTPUT_KEY
          valueFrom:
            configMapKeyRef:
              name: outputkey
              key: REDIS_OUTPUT_KEY
        volumeMounts:
        - name: pyfile-config-volume
          mountPath: /app/config  # Mount the ConfigMap containing handler.py here
      volumes:
      - name: pyfile-config-volume
        configMap:
          name: pyfile  # Reference to the ConfigMap containing handler.py
